spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

jpa:
  database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9090